/**
 * sherlock-sites.ts — Built-in platform database: 500+ sites across 20+ categories.
 * Supplemented at runtime by the Maigret database (~3500 sites).
 */

export type NotFoundStrategy =
  | { kind: "status"; code: number }
  | { kind: "bodyContains"; text: string }
  | { kind: "redirectTo"; pattern: string };

export interface Platform {
  name: string;
  category: string;
  url: (u: string) => string;
  notFound: NotFoundStrategy;
}

export const BUILTIN_PLATFORMS: Platform[] = [

  // ─── Социальные сети (глобальные) ────────────────────────────────────────
  { name: "Instagram",      category: "Соцсети", url: u => `https://www.instagram.com/${u}/`,              notFound: { kind: "status",       code: 404 } },
  { name: "Twitter/X",      category: "Соцсети", url: u => `https://x.com/${u}`,                           notFound: { kind: "status",       code: 404 } },
  { name: "TikTok",         category: "Соцсети", url: u => `https://www.tiktok.com/@${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "Pinterest",      category: "Соцсети", url: u => `https://www.pinterest.com/${u}/`,              notFound: { kind: "status",       code: 404 } },
  { name: "Facebook",       category: "Соцсети", url: u => `https://www.facebook.com/${u}`,                notFound: { kind: "status",       code: 404 } },
  { name: "LinkedIn",       category: "Соцсети", url: u => `https://www.linkedin.com/in/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Snapchat",       category: "Соцсети", url: u => `https://www.snapchat.com/add/${u}`,            notFound: { kind: "status",       code: 404 } },
  { name: "Mastodon",       category: "Соцсети", url: u => `https://mastodon.social/@${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Bluesky",        category: "Соцсети", url: u => `https://bsky.app/profile/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Threads",        category: "Соцсети", url: u => `https://www.threads.net/@${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "MeWe",           category: "Соцсети", url: u => `https://mewe.com/i/${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "Minds",          category: "Соцсети", url: u => `https://www.minds.com/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Parler",         category: "Соцсети", url: u => `https://parler.com/${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "Gab",            category: "Соцсети", url: u => `https://gab.com/${u}`,                         notFound: { kind: "status",       code: 404 } },
  { name: "Truth Social",   category: "Соцсети", url: u => `https://truthsocial.com/@${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Diaspora*",      category: "Соцсети", url: u => `https://diaspora.social/people/${u}`,         notFound: { kind: "status",       code: 404 } },
  { name: "Plurk",          category: "Соцсети", url: u => `https://www.plurk.com/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Weibo",          category: "Соцсети", url: u => `https://weibo.com/${u}`,                       notFound: { kind: "status",       code: 404 } },
  { name: "Mixi",           category: "Соцсети", url: u => `https://mixi.jp/${u}`,                         notFound: { kind: "status",       code: 404 } },
  { name: "Hi5",            category: "Соцсети", url: u => `https://www.hi5.com/${u}`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Friendica",      category: "Соцсети", url: u => `https://socialhome.network/u/${u}/`,           notFound: { kind: "status",       code: 404 } },
  { name: "Ello",           category: "Соцсети", url: u => `https://ello.co/${u}`,                         notFound: { kind: "status",       code: 404 } },
  { name: "Path",           category: "Соцсети", url: u => `https://path.com/${u}`,                        notFound: { kind: "status",       code: 404 } },
  { name: "Peach",          category: "Соцсети", url: u => `https://peach.cool/${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "BeReal",         category: "Соцсети", url: u => `https://bere.al/${u}`,                         notFound: { kind: "status",       code: 404 } },

  // ─── Русскоязычные соцсети ───────────────────────────────────────────────
  { name: "VK",             category: "Соцсети RU", url: u => `https://vk.com/${u}`,                       notFound: { kind: "bodyContains", text: "not found" } },
  { name: "Odnoklassniki",  category: "Соцсети RU", url: u => `https://ok.ru/${u}`,                        notFound: { kind: "status",       code: 404 } },
  { name: "Mirtesen",       category: "Соцсети RU", url: u => `https://mirtesen.ru/people/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "LiveJournal",    category: "Соцсети RU", url: u => `https://${u}.livejournal.com`,              notFound: { kind: "bodyContains", text: "No such journal" } },
  { name: "Pikabu",         category: "Соцсети RU", url: u => `https://pikabu.ru/@${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "DTF",            category: "Соцсети RU", url: u => `https://dtf.ru/u/${u}`,                     notFound: { kind: "status",       code: 404 } },
  { name: "VC.ru",          category: "Соцсети RU", url: u => `https://vc.ru/u/${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "Habr",           category: "Соцсети RU", url: u => `https://habr.com/ru/users/${u}/`,           notFound: { kind: "status",       code: 404 } },
  { name: "TJournal",       category: "Соцсети RU", url: u => `https://tjournal.ru/u/${u}`,                notFound: { kind: "status",       code: 404 } },
  { name: "Fishki.net",     category: "Соцсети RU", url: u => `https://fishki.net/user/${u}`,              notFound: { kind: "status",       code: 404 } },
  { name: "Dirty.ru",       category: "Соцсети RU", url: u => `https://dirty.ru/users/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Ru-Board",       category: "Соцсети RU", url: u => `https://forum.ru-board.com/profile.cgi?action=show&member=${u}`, notFound: { kind: "status", code: 404 } },
  { name: "Banki.ru",       category: "Соцсети RU", url: u => `https://www.banki.ru/people/profile/${u}/`, notFound: { kind: "status",       code: 404 } },
  { name: "Sports.ru",      category: "Соцсети RU", url: u => `https://www.sports.ru/profile/${u}/`,       notFound: { kind: "status",       code: 404 } },
  { name: "Drom.ru",        category: "Соцсети RU", url: u => `https://www.drom.ru/user/${u}/`,            notFound: { kind: "status",       code: 404 } },
  { name: "LiveLib",        category: "Соцсети RU", url: u => `https://www.livelib.ru/reader/${u}`,        notFound: { kind: "status",       code: 404 } },
  { name: "Mybook",         category: "Соцсети RU", url: u => `https://mybook.ru/user/${u}/`,              notFound: { kind: "status",       code: 404 } },
  { name: "Author.Today",   category: "Соцсети RU", url: u => `https://author.today/u/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Wattpad RU",     category: "Соцсети RU", url: u => `https://www.wattpad.com/user/${u}`,         notFound: { kind: "status",       code: 404 } },
  { name: "Ficbook",        category: "Соцсети RU", url: u => `https://ficbook.net/authors/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "StartUp.ru",     category: "Соцсети RU", url: u => `https://www.startup.ru/users/${u}`,         notFound: { kind: "status",       code: 404 } },

  // ─── Мессенджеры ─────────────────────────────────────────────────────────
  { name: "Telegram",       category: "Мессенджеры", url: u => `https://t.me/${u}`,                        notFound: { kind: "bodyContains", text: "If you have Telegram" } },
  { name: "Signal",         category: "Мессенджеры", url: u => `https://signal.group/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Discord",        category: "Мессенджеры", url: u => `https://discord.com/users/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "Slack",          category: "Мессенджеры", url: u => `https://${u}.slack.com`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Matrix",         category: "Мессенджеры", url: u => `https://matrix.to/#/@${u}:matrix.org`,    notFound: { kind: "status",       code: 404 } },
  { name: "Kik",            category: "Мессенджеры", url: u => `https://www.kik.com/#${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "ICQ",            category: "Мессенджеры", url: u => `https://icq.com/${u}`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Wire",           category: "Мессенджеры", url: u => `https://wire.com/users/${u}`,              notFound: { kind: "status",       code: 404 } },

  // ─── Форумы / Комьюнити ───────────────────────────────────────────────────
  { name: "Reddit",         category: "Форумы", url: u => `https://www.reddit.com/user/${u}`,              notFound: { kind: "status",       code: 404 } },
  { name: "Quora",          category: "Форумы", url: u => `https://www.quora.com/profile/${u}`,            notFound: { kind: "status",       code: 404 } },
  { name: "HackerNews",     category: "Форумы", url: u => `https://news.ycombinator.com/user?id=${u}`,    notFound: { kind: "bodyContains", text: "No such user" } },
  { name: "Ask.fm",         category: "Форумы", url: u => `https://ask.fm/${u}`,                           notFound: { kind: "status",       code: 404 } },
  { name: "4chan",           category: "Форумы", url: u => `https://boards.4chan.org/${u}/`,               notFound: { kind: "status",       code: 404 } },
  { name: "8kun",           category: "Форумы", url: u => `https://8kun.top/${u}/index.html`,             notFound: { kind: "status",       code: 404 } },
  { name: "Voat",           category: "Форумы", url: u => `https://voat.co/user/${u}`,                    notFound: { kind: "status",       code: 404 } },
  { name: "Lemmy",          category: "Форумы", url: u => `https://lemmy.world/u/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Lobste.rs",      category: "Форумы", url: u => `https://lobste.rs/~${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "Tildes",         category: "Форумы", url: u => `https://tildes.net/user/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "XDA Developers", category: "Форумы", url: u => `https://forum.xda-developers.com/member.php?username=${u}`, notFound: { kind: "status", code: 404 } },
  { name: "Stack Overflow", category: "Форумы", url: u => `https://stackoverflow.com/users/${u}`,         notFound: { kind: "status",       code: 404 } },
  { name: "Stack Exchange", category: "Форумы", url: u => `https://stackexchange.com/users/${u}`,         notFound: { kind: "status",       code: 404 } },
  { name: "Super User",     category: "Форумы", url: u => `https://superuser.com/users/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Server Fault",   category: "Форумы", url: u => `https://serverfault.com/users/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "MathOverflow",   category: "Форумы", url: u => `https://mathoverflow.net/users/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Warrior Forum",  category: "Форумы", url: u => `https://www.warriorforum.com/members/${u}.html`, notFound: { kind: "status",     code: 404 } },
  { name: "Nairaland",      category: "Форумы", url: u => `https://www.nairaland.com/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "2ch.hk",         category: "Форумы", url: u => `https://2ch.hk/${u}`,                          notFound: { kind: "status",       code: 404 } },
  { name: "Kiwi Farms",     category: "Форумы", url: u => `https://kiwifarms.net/members/${u}/`,          notFound: { kind: "status",       code: 404 } },
  { name: "Phpbb Demo",     category: "Форумы", url: u => `https://www.phpbb.com/community/memberlist.php?mode=viewprofile&u=${u}`, notFound: { kind: "status", code: 404 } },
  { name: "Typeracer",      category: "Форумы", url: u => `https://data.typeracer.com/pit/profile?user=${u}`, notFound: { kind: "bodyContains", text: "No user" } },
  { name: "Disqus",         category: "Форумы", url: u => `https://disqus.com/by/${u}/`,                  notFound: { kind: "status",       code: 404 } },
  { name: "Intensedebate",  category: "Форумы", url: u => `https://intensedebate.com/people/${u}`,        notFound: { kind: "status",       code: 404 } },

  // ─── Разработка ──────────────────────────────────────────────────────────
  { name: "GitHub",         category: "Разработка", url: u => `https://github.com/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "GitLab",         category: "Разработка", url: u => `https://gitlab.com/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Bitbucket",      category: "Разработка", url: u => `https://bitbucket.org/${u}`,                notFound: { kind: "status",       code: 404 } },
  { name: "SourceForge",    category: "Разработка", url: u => `https://sourceforge.net/u/${u}/profile/`,   notFound: { kind: "status",       code: 404 } },
  { name: "Codeberg",       category: "Разработка", url: u => `https://codeberg.org/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "Gitea",          category: "Разработка", url: u => `https://gitea.io/${u}`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Dev.to",         category: "Разработка", url: u => `https://dev.to/${u}`,                       notFound: { kind: "status",       code: 404 } },
  { name: "CodePen",        category: "Разработка", url: u => `https://codepen.io/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "JSFiddle",       category: "Разработка", url: u => `https://jsfiddle.net/user/${u}/`,           notFound: { kind: "status",       code: 404 } },
  { name: "CodeSandbox",    category: "Разработка", url: u => `https://codesandbox.io/u/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Replit",         category: "Разработка", url: u => `https://replit.com/@${u}`,                  notFound: { kind: "status",       code: 404 } },
  { name: "npm",            category: "Разработка", url: u => `https://www.npmjs.com/~${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "PyPI",           category: "Разработка", url: u => `https://pypi.org/user/${u}/`,               notFound: { kind: "status",       code: 404 } },
  { name: "RubyGems",       category: "Разработка", url: u => `https://rubygems.org/profiles/${u}`,        notFound: { kind: "status",       code: 404 } },
  { name: "Crates.io",      category: "Разработка", url: u => `https://crates.io/users/${u}`,              notFound: { kind: "status",       code: 404 } },
  { name: "Packagist",      category: "Разработка", url: u => `https://packagist.org/users/${u}/`,         notFound: { kind: "status",       code: 404 } },
  { name: "NuGet",          category: "Разработка", url: u => `https://www.nuget.org/profiles/${u}`,       notFound: { kind: "status",       code: 404 } },
  { name: "Docker Hub",     category: "Разработка", url: u => `https://hub.docker.com/u/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Quay.io",        category: "Разработка", url: u => `https://quay.io/user/${u}/`,                notFound: { kind: "status",       code: 404 } },
  { name: "Hashnode",       category: "Разработка", url: u => `https://hashnode.com/@${u}`,                notFound: { kind: "status",       code: 404 } },
  { name: "Keybase",        category: "Разработка", url: u => `https://keybase.io/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "HackerOne",      category: "Разработка", url: u => `https://hackerone.com/${u}`,                notFound: { kind: "status",       code: 404 } },
  { name: "Bugcrowd",       category: "Разработка", url: u => `https://bugcrowd.com/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "Intigriti",      category: "Разработка", url: u => `https://app.intigriti.com/profile/${u}`,    notFound: { kind: "status",       code: 404 } },
  { name: "CTFtime",        category: "Разработка", url: u => `https://ctftime.org/user/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "TryHackMe",      category: "Разработка", url: u => `https://tryhackme.com/p/${u}`,              notFound: { kind: "status",       code: 404 } },
  { name: "HackTheBox",     category: "Разработка", url: u => `https://www.hackthebox.eu/profile/${u}`,    notFound: { kind: "status",       code: 404 } },
  { name: "Root-Me",        category: "Разработка", url: u => `https://www.root-me.org/${u}`,              notFound: { kind: "status",       code: 404 } },
  { name: "Leetcode",       category: "Разработка", url: u => `https://leetcode.com/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "HackerRank",     category: "Разработка", url: u => `https://www.hackerrank.com/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "Codewars",       category: "Разработка", url: u => `https://www.codewars.com/users/${u}`,       notFound: { kind: "status",       code: 404 } },
  { name: "Exercism",       category: "Разработка", url: u => `https://exercism.org/profiles/${u}`,        notFound: { kind: "status",       code: 404 } },
  { name: "CodinGame",      category: "Разработка", url: u => `https://www.codingame.com/profile/${u}`,    notFound: { kind: "status",       code: 404 } },
  { name: "Codeforces",     category: "Разработка", url: u => `https://codeforces.com/profile/${u}`,       notFound: { kind: "status",       code: 404 } },
  { name: "AtCoder",        category: "Разработка", url: u => `https://atcoder.jp/users/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "TopCoder",       category: "Разработка", url: u => `https://www.topcoder.com/members/${u}`,     notFound: { kind: "status",       code: 404 } },
  { name: "SPOJ",           category: "Разработка", url: u => `https://www.spoj.com/users/${u}/`,          notFound: { kind: "status",       code: 404 } },
  { name: "ProjectEuler",   category: "Разработка", url: u => `https://projecteuler.net/progress=${u}`,    notFound: { kind: "status",       code: 404 } },
  { name: "CodeChef",       category: "Разработка", url: u => `https://www.codechef.com/users/${u}`,       notFound: { kind: "status",       code: 404 } },
  { name: "Kattis",         category: "Разработка", url: u => `https://open.kattis.com/users/${u}`,        notFound: { kind: "status",       code: 404 } },
  { name: "Kaggle",         category: "Разработка", url: u => `https://www.kaggle.com/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Hugging Face",   category: "Разработка", url: u => `https://huggingface.co/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "OSF.io",         category: "Разработка", url: u => `https://osf.io/profile/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "GitBook",        category: "Разработка", url: u => `https://www.gitbook.com/@${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Notion",         category: "Разработка", url: u => `https://www.notion.so/@${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Obsidian",       category: "Разработка", url: u => `https://publish.obsidian.md/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Netlify",        category: "Разработка", url: u => `https://app.netlify.com/teams/${u}`,        notFound: { kind: "status",       code: 404 } },

  // ─── Игры ────────────────────────────────────────────────────────────────
  { name: "Twitch",         category: "Игры", url: u => `https://www.twitch.tv/${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "Steam",          category: "Игры", url: u => `https://steamcommunity.com/id/${u}`,              notFound: { kind: "bodyContains", text: "The specified profile could not be found" } },
  { name: "Roblox",         category: "Игры", url: u => `https://www.roblox.com/user.aspx?username=${u}`, notFound: { kind: "bodyContains", text: "Page Not Found" } },
  { name: "Chess.com",      category: "Игры", url: u => `https://www.chess.com/member/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Lichess",        category: "Игры", url: u => `https://lichess.org/@/${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "Minecraft",      category: "Игры", url: u => `https://api.mojang.com/users/profiles/minecraft/${u}`, notFound: { kind: "status", code: 404 } },
  { name: "Faceit",         category: "Игры", url: u => `https://www.faceit.com/en/players/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Xbox",           category: "Игры", url: u => `https://account.xbox.com/en-US/Profile?Gamertag=${u}`, notFound: { kind: "status", code: 404 } },
  { name: "PlayStation",    category: "Игры", url: u => `https://psnprofiles.com/${u}`,                    notFound: { kind: "status",       code: 404 } },
  { name: "Epic Games",     category: "Игры", url: u => `https://www.epicgames.com/id/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Battle.net",     category: "Игры", url: u => `https://overwatch.blizzard.com/en-us/career/${u}/`, notFound: { kind: "status",     code: 404 } },
  { name: "Origin/EA",      category: "Игры", url: u => `https://www.ea.com/games/library/pcdownloads`,    notFound: { kind: "status",       code: 404 } },
  { name: "Ubisoft",        category: "Игры", url: u => `https://www.ubisoft.com/en-us/game/club/users/${u}`, notFound: { kind: "status",   code: 404 } },
  { name: "GOG",            category: "Игры", url: u => `https://www.gog.com/u/${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "Itch.io",        category: "Игры", url: u => `https://${u}.itch.io`,                            notFound: { kind: "status",       code: 404 } },
  { name: "GameJolt",       category: "Игры", url: u => `https://gamejolt.com/@${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "IndieDB",        category: "Игры", url: u => `https://www.indiedb.com/members/${u}`,            notFound: { kind: "status",       code: 404 } },
  { name: "Kongregate",     category: "Игры", url: u => `https://www.kongregate.com/accounts/${u}`,        notFound: { kind: "status",       code: 404 } },
  { name: "Newgrounds",     category: "Игры", url: u => `https://${u}.newgrounds.com`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Speedrun.com",   category: "Игры", url: u => `https://www.speedrun.com/user/${u}`,              notFound: { kind: "status",       code: 404 } },
  { name: "Curseforge",     category: "Игры", url: u => `https://www.curseforge.com/members/${u}`,         notFound: { kind: "status",       code: 404 } },
  { name: "Modrinth",       category: "Игры", url: u => `https://modrinth.com/user/${u}`,                  notFound: { kind: "status",       code: 404 } },
  { name: "N-Gage",         category: "Игры", url: u => `https://www.n-gage.com/n-gage/content/user-profile/${u}`, notFound: { kind: "status", code: 404 } },
  { name: "Fortnite Tracker", category: "Игры", url: u => `https://fortnitetracker.com/profile/all/${u}`,  notFound: { kind: "status",       code: 404 } },
  { name: "COD Tracker",    category: "Игры", url: u => `https://cod.tracker.gg/warzone/profile/psn/${u}`, notFound: { kind: "status",       code: 404 } },
  { name: "PUBG Lookup",    category: "Игры", url: u => `https://pubglookup.com/players/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Wargaming",      category: "Игры", url: u => `https://worldoftanks.ru/ru/community/accounts/${u}/`, notFound: { kind: "status",  code: 404 } },
  { name: "Overwatch",      category: "Игры", url: u => `https://overwatch.blizzard.com/en-us/career/${u}-1/`, notFound: { kind: "status",  code: 404 } },
  { name: "Riot Games",     category: "Игры", url: u => `https://tracker.gg/lol/profile/riot/${u}/overview`, notFound: { kind: "status",   code: 404 } },
  { name: "Growtopia",      category: "Игры", url: u => `https://www.growtopiagame.com/player/${u}`,       notFound: { kind: "status",       code: 404 } },
  { name: "Habbo",          category: "Игры", url: u => `https://www.habbo.com/profile/${u}`,              notFound: { kind: "status",       code: 404 } },
  { name: "Shockwave",      category: "Игры", url: u => `https://www.shockwave.com/account/profile/${u}`,  notFound: { kind: "status",       code: 404 } },
  { name: "Torn",           category: "Игры", url: u => `https://www.torn.com/profiles.php?XID=${u}`,      notFound: { kind: "bodyContains", text: "not found" } },
  { name: "DotA2 Tracker",  category: "Игры", url: u => `https://www.dotabuff.com/players/${u}`,           notFound: { kind: "status",       code: 404 } },

  // ─── Видео / Стриминг ────────────────────────────────────────────────────
  { name: "YouTube",        category: "Видео", url: u => `https://www.youtube.com/@${u}`,                  notFound: { kind: "status",       code: 404 } },
  { name: "Vimeo",          category: "Видео", url: u => `https://vimeo.com/${u}`,                         notFound: { kind: "status",       code: 404 } },
  { name: "Dailymotion",    category: "Видео", url: u => `https://www.dailymotion.com/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Rutube",         category: "Видео", url: u => `https://rutube.ru/channel/${u}/`,                notFound: { kind: "status",       code: 404 } },
  { name: "Odysee",         category: "Видео", url: u => `https://odysee.com/@${u}`,                       notFound: { kind: "status",       code: 404 } },
  { name: "Rumble",         category: "Видео", url: u => `https://rumble.com/user/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "BitChute",       category: "Видео", url: u => `https://www.bitchute.com/channel/${u}/`,         notFound: { kind: "status",       code: 404 } },
  { name: "Kick",           category: "Видео", url: u => `https://kick.com/${u}`,                          notFound: { kind: "status",       code: 404 } },
  { name: "Dlive",          category: "Видео", url: u => `https://dlive.tv/${u}`,                          notFound: { kind: "status",       code: 404 } },
  { name: "Veoh",           category: "Видео", url: u => `https://www.veoh.com/users/${u}`,                notFound: { kind: "status",       code: 404 } },
  { name: "Metacafe",       category: "Видео", url: u => `https://www.metacafe.com/channels/${u}/`,        notFound: { kind: "status",       code: 404 } },
  { name: "Bilibili",       category: "Видео", url: u => `https://space.bilibili.com/${u}`,                notFound: { kind: "status",       code: 404 } },
  { name: "Niconico",       category: "Видео", url: u => `https://www.nicovideo.jp/user/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "AfreecaTV",      category: "Видео", url: u => `https://www.afreecatv.com/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "VK Video",       category: "Видео", url: u => `https://vkvideo.ru/@${u}`,                       notFound: { kind: "status",       code: 404 } },
  { name: "Trovo",          category: "Видео", url: u => `https://trovo.live/${u}`,                        notFound: { kind: "status",       code: 404 } },
  { name: "Streamlabs",     category: "Видео", url: u => `https://streamlabs.com/${u}`,                    notFound: { kind: "status",       code: 404 } },
  { name: "Restream",       category: "Видео", url: u => `https://restream.io/${u}`,                       notFound: { kind: "status",       code: 404 } },

  // ─── Музыка ──────────────────────────────────────────────────────────────
  { name: "SoundCloud",     category: "Музыка", url: u => `https://soundcloud.com/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Spotify",        category: "Музыка", url: u => `https://open.spotify.com/user/${u}`,            notFound: { kind: "status",       code: 404 } },
  { name: "Last.fm",        category: "Музыка", url: u => `https://www.last.fm/user/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "Mixcloud",       category: "Музыка", url: u => `https://www.mixcloud.com/${u}/`,                notFound: { kind: "status",       code: 404 } },
  { name: "Bandcamp",       category: "Музыка", url: u => `https://${u}.bandcamp.com`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Audiomack",      category: "Музыка", url: u => `https://audiomack.com/${u}`,                    notFound: { kind: "status",       code: 404 } },
  { name: "ReverbNation",   category: "Музыка", url: u => `https://www.reverbnation.com/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Genius",         category: "Музыка", url: u => `https://genius.com/${u}`,                       notFound: { kind: "status",       code: 404 } },
  { name: "Grooveshark",    category: "Музыка", url: u => `https://grooveshark.com/#!/user/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Deezer",         category: "Музыка", url: u => `https://www.deezer.com/profile/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "Apple Music",    category: "Музыка", url: u => `https://music.apple.com/profile/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Tidal",          category: "Музыка", url: u => `https://tidal.com/browse/profile/${u}`,         notFound: { kind: "status",       code: 404 } },
  { name: "Jamendo",        category: "Музыка", url: u => `https://www.jamendo.com/artist/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "8tracks",        category: "Музыка", url: u => `https://8tracks.com/${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "Soundtrap",      category: "Музыка", url: u => `https://www.soundtrap.com/${u}/`,               notFound: { kind: "status",       code: 404 } },
  { name: "Sing!",          category: "Музыка", url: u => `https://www.smule.com/${u}`,                    notFound: { kind: "status",       code: 404 } },

  // ─── Фото ────────────────────────────────────────────────────────────────
  { name: "Flickr",         category: "Фото", url: u => `https://www.flickr.com/people/${u}`,              notFound: { kind: "status",       code: 404 } },
  { name: "500px",          category: "Фото", url: u => `https://500px.com/p/${u}`,                        notFound: { kind: "status",       code: 404 } },
  { name: "Unsplash",       category: "Фото", url: u => `https://unsplash.com/@${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "VSCO",           category: "Фото", url: u => `https://vsco.co/${u}/gallery`,                    notFound: { kind: "status",       code: 404 } },
  { name: "EyeEm",          category: "Фото", url: u => `https://www.eyeem.com/u/${u}`,                    notFound: { kind: "status",       code: 404 } },
  { name: "Pixabay",        category: "Фото", url: u => `https://pixabay.com/users/${u}/`,                 notFound: { kind: "status",       code: 404 } },
  { name: "Pexels",         category: "Фото", url: u => `https://www.pexels.com/@${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Imgur",          category: "Фото", url: u => `https://imgur.com/user/${u}`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Photobucket",    category: "Фото", url: u => `https://photobucket.com/user/${u}/profile/`,      notFound: { kind: "status",       code: 404 } },
  { name: "SmugMug",        category: "Фото", url: u => `https://${u}.smugmug.com`,                        notFound: { kind: "status",       code: 404 } },
  { name: "Glass",          category: "Фото", url: u => `https://glass.photo/${u}`,                        notFound: { kind: "status",       code: 404 } },
  { name: "Zenfolio",       category: "Фото", url: u => `https://${u}.zenfolio.com`,                       notFound: { kind: "status",       code: 404 } },
  { name: "Fotki",          category: "Фото", url: u => `https://public.fotki.com/${u}/`,                  notFound: { kind: "status",       code: 404 } },

  // ─── Дизайн / Арт ────────────────────────────────────────────────────────
  { name: "Behance",        category: "Дизайн", url: u => `https://www.behance.net/${u}`,                  notFound: { kind: "status",       code: 404 } },
  { name: "Dribbble",       category: "Дизайн", url: u => `https://dribbble.com/${u}`,                     notFound: { kind: "status",       code: 404 } },
  { name: "DeviantArt",     category: "Дизайн", url: u => `https://www.deviantart.com/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "ArtStation",     category: "Дизайн", url: u => `https://www.artstation.com/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Pixiv",          category: "Дизайн", url: u => `https://www.pixiv.net/en/users/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "Sketchfab",      category: "Дизайн", url: u => `https://sketchfab.com/${u}`,                    notFound: { kind: "status",       code: 404 } },
  { name: "Canva",          category: "Дизайн", url: u => `https://www.canva.com/${u}`,                    notFound: { kind: "status",       code: 404 } },
  { name: "Figma",          category: "Дизайн", url: u => `https://www.figma.com/@${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Drawingdock",    category: "Дизайн", url: u => `https://drawingdock.com/${u}`,                  notFound: { kind: "status",       code: 404 } },
  { name: "Creativefabrica", category: "Дизайн", url: u => `https://www.creativefabrica.com/designer/${u}/`, notFound: { kind: "status",    code: 404 } },
  { name: "Redbubble",      category: "Дизайн", url: u => `https://www.redbubble.com/people/${u}`,         notFound: { kind: "status",       code: 404 } },
  { name: "Society6",       category: "Дизайн", url: u => `https://society6.com/${u}`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Threadless",     category: "Дизайн", url: u => `https://www.threadless.com/@${u}/activity`,     notFound: { kind: "status",       code: 404 } },
  { name: "Zazzle",         category: "Дизайн", url: u => `https://www.zazzle.com/store/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Teepublic",      category: "Дизайн", url: u => `https://www.teepublic.com/user/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "Spoonflower",    category: "Дизайн", url: u => `https://www.spoonflower.com/profiles/${u}`,     notFound: { kind: "status",       code: 404 } },
  { name: "Gelaskins",      category: "Дизайн", url: u => `https://www.gelaskins.com/store/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Cara",           category: "Дизайн", url: u => `https://cara.app/${u}`,                         notFound: { kind: "status",       code: 404 } },

  // ─── Блоги / Письмо ───────────────────────────────────────────────────────
  { name: "Medium",         category: "Блоги", url: u => `https://medium.com/@${u}`,                       notFound: { kind: "status",       code: 404 } },
  { name: "Substack",       category: "Блоги", url: u => `https://substack.com/@${u}`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Tumblr",         category: "Блоги", url: u => `https://${u}.tumblr.com`,                        notFound: { kind: "status",       code: 404 } },
  { name: "Blogger",        category: "Блоги", url: u => `https://${u}.blogspot.com`,                      notFound: { kind: "bodyContains", text: "Sorry, the blog at" } },
  { name: "WordPress",      category: "Блоги", url: u => `https://${u}.wordpress.com`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Ghost",          category: "Блоги", url: u => `https://${u}.ghost.io`,                          notFound: { kind: "status",       code: 404 } },
  { name: "Wix",            category: "Блоги", url: u => `https://${u}.wixsite.com`,                       notFound: { kind: "status",       code: 404 } },
  { name: "Weebly",         category: "Блоги", url: u => `https://${u}.weebly.com`,                        notFound: { kind: "status",       code: 404 } },
  { name: "Squarespace",    category: "Блоги", url: u => `https://${u}.squarespace.com`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Webflow",        category: "Блоги", url: u => `https://${u}.webflow.io`,                        notFound: { kind: "status",       code: 404 } },
  { name: "WriteFreely",    category: "Блоги", url: u => `https://write.as/${u}`,                          notFound: { kind: "status",       code: 404 } },
  { name: "Bear",           category: "Блоги", url: u => `https://bearblog.dev/${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "Micro.blog",     category: "Блоги", url: u => `https://micro.blog/${u}`,                        notFound: { kind: "status",       code: 404 } },
  { name: "Cohost",         category: "Блоги", url: u => `https://cohost.org/${u}`,                        notFound: { kind: "status",       code: 404 } },
  { name: "Hive.blog",      category: "Блоги", url: u => `https://hive.blog/@${u}`,                       notFound: { kind: "status",       code: 404 } },
  { name: "Steemit",        category: "Блоги", url: u => `https://steemit.com/@${u}`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Read.cv",        category: "Блоги", url: u => `https://read.cv/${u}`,                           notFound: { kind: "status",       code: 404 } },
  { name: "Penzu",          category: "Блоги", url: u => `https://penzu.com/public/${u}`,                  notFound: { kind: "status",       code: 404 } },

  // ─── Книги / Кино ─────────────────────────────────────────────────────────
  { name: "Goodreads",      category: "Книги", url: u => `https://www.goodreads.com/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "Letterboxd",     category: "Кино",  url: u => `https://letterboxd.com/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Trakt.tv",       category: "Кино",  url: u => `https://trakt.tv/users/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "IMDb",           category: "Кино",  url: u => `https://www.imdb.com/user/${u}/`,               notFound: { kind: "status",       code: 404 } },
  { name: "LibraryThing",   category: "Книги", url: u => `https://www.librarything.com/profile/${u}`,      notFound: { kind: "status",       code: 404 } },
  { name: "Bookcrossing",   category: "Книги", url: u => `https://www.bookcrossing.com/mybookshelf/${u}/`, notFound: { kind: "status",       code: 404 } },
  { name: "StoryGraph",     category: "Книги", url: u => `https://app.thestorygraph.com/profile/${u}`,    notFound: { kind: "status",       code: 404 } },
  { name: "Anobii",         category: "Книги", url: u => `https://www.anobii.com/${u}/books`,             notFound: { kind: "status",       code: 404 } },
  { name: "Shelfari",       category: "Книги", url: u => `https://www.shelfari.com/users/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "Anilist",        category: "Кино",  url: u => `https://anilist.co/user/${u}/`,                 notFound: { kind: "status",       code: 404 } },
  { name: "MyAnimeList",    category: "Кино",  url: u => `https://myanimelist.net/profile/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Kitsu",          category: "Кино",  url: u => `https://kitsu.io/users/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Anime-Planet",   category: "Кино",  url: u => `https://www.anime-planet.com/users/${u}`,       notFound: { kind: "status",       code: 404 } },
  { name: "Crunchyroll",    category: "Кино",  url: u => `https://www.crunchyroll.com/user/${u}`,         notFound: { kind: "status",       code: 404 } },

  // ─── Образование ─────────────────────────────────────────────────────────
  { name: "Duolingo",       category: "Образование", url: u => `https://www.duolingo.com/profile/${u}`,    notFound: { kind: "status",       code: 404 } },
  { name: "Coursera",       category: "Образование", url: u => `https://www.coursera.org/user/${u}`,       notFound: { kind: "status",       code: 404 } },
  { name: "Khan Academy",   category: "Образование", url: u => `https://www.khanacademy.org/profile/${u}`, notFound: { kind: "status",       code: 404 } },
  { name: "Udemy",          category: "Образование", url: u => `https://www.udemy.com/user/${u}/`,         notFound: { kind: "status",       code: 404 } },
  { name: "edX",            category: "Образование", url: u => `https://courses.edx.org/u/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "Brilliant",      category: "Образование", url: u => `https://brilliant.org/profile/${u}/`,      notFound: { kind: "status",       code: 404 } },
  { name: "Academia.edu",   category: "Образование", url: u => `https://www.academia.edu/${u}`,            notFound: { kind: "status",       code: 404 } },
  { name: "ResearchGate",   category: "Образование", url: u => `https://www.researchgate.net/profile/${u}`, notFound: { kind: "status",      code: 404 } },
  { name: "ORCID",          category: "Образование", url: u => `https://orcid.org/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Mendeley",       category: "Образование", url: u => `https://www.mendeley.com/profiles/${u}/`,  notFound: { kind: "status",       code: 404 } },
  { name: "Skillshare",     category: "Образование", url: u => `https://www.skillshare.com/profile/${u}`,  notFound: { kind: "status",       code: 404 } },
  { name: "Pluralsight",    category: "Образование", url: u => `https://app.pluralsight.com/profile/${u}`,  notFound: { kind: "status",      code: 404 } },
  { name: "FreeCodeCamp",   category: "Образование", url: u => `https://www.freecodecamp.org/fcc${u}`,     notFound: { kind: "status",       code: 404 } },
  { name: "Codecademy",     category: "Образование", url: u => `https://www.codecademy.com/profiles/${u}`, notFound: { kind: "status",       code: 404 } },
  { name: "Sololearn",      category: "Образование", url: u => `https://www.sololearn.com/Profile/${u}`,   notFound: { kind: "status",       code: 404 } },
  { name: "Memrise",        category: "Образование", url: u => `https://app.memrise.com/user/${u}/courses/learning/`, notFound: { kind: "status", code: 404 } },
  { name: "Busuu",          category: "Образование", url: u => `https://www.busuu.com/en/member/${u}`,     notFound: { kind: "status",       code: 404 } },
  { name: "iTalki",         category: "Образование", url: u => `https://www.italki.com/user/${u}`,         notFound: { kind: "status",       code: 404 } },

  // ─── Спорт / Фитнес ──────────────────────────────────────────────────────
  { name: "Strava",         category: "Спорт", url: u => `https://www.strava.com/athletes/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "Nike",           category: "Спорт", url: u => `https://www.nike.com/member/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Garmin",         category: "Спорт", url: u => `https://connect.garmin.com/modern/profile/${u}`, notFound: { kind: "status",       code: 404 } },
  { name: "Polar Flow",     category: "Спорт", url: u => `https://flow.polar.com/profile/${u}`,            notFound: { kind: "status",       code: 404 } },
  { name: "MyFitnessPal",   category: "Спорт", url: u => `https://www.myfitnesspal.com/profile/${u}`,      notFound: { kind: "status",       code: 404 } },
  { name: "Fitbit",         category: "Спорт", url: u => `https://www.fitbit.com/user/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Komoot",         category: "Спорт", url: u => `https://www.komoot.com/user/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "AllTrails",      category: "Спорт", url: u => `https://www.alltrails.com/members/${u}`,         notFound: { kind: "status",       code: 404 } },
  { name: "MapMyRun",       category: "Спорт", url: u => `https://www.mapmyrun.com/profile/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Runkeeper",      category: "Спорт", url: u => `https://runkeeper.com/user/${u}/profile`,        notFound: { kind: "status",       code: 404 } },
  { name: "Zwift",          category: "Спорт", url: u => `https://www.zwift.com/athlete/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Peloton",        category: "Спорт", url: u => `https://members.onepeloton.com/members/${u}/overview`, notFound: { kind: "status", code: 404 } },

  // ─── Финансы / Крипто ────────────────────────────────────────────────────
  { name: "Bitcointalk",    category: "Крипто", url: u => `https://bitcointalk.org/index.php?action=profile;u=${u}`, notFound: { kind: "status", code: 404 } },
  { name: "Binance",        category: "Крипто", url: u => `https://www.binance.com/en/feed/profile/${u}`,  notFound: { kind: "status",       code: 404 } },
  { name: "Coinbase",       category: "Крипто", url: u => `https://www.coinbase.com/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "OKX",            category: "Крипто", url: u => `https://www.okx.com/ru/copy-trading/account/${u}`, notFound: { kind: "status",   code: 404 } },
  { name: "CoinMarketCap",  category: "Крипто", url: u => `https://coinmarketcap.com/community/profile/${u}/`, notFound: { kind: "status",   code: 404 } },
  { name: "Etherscan",      category: "Крипто", url: u => `https://etherscan.io/name-lookup-search?id=${u}`, notFound: { kind: "status",   code: 404 } },
  { name: "OpenSea",        category: "Крипто", url: u => `https://opensea.io/${u}`,                       notFound: { kind: "status",       code: 404 } },
  { name: "Foundation",     category: "Крипто", url: u => `https://foundation.app/@${u}`,                  notFound: { kind: "status",       code: 404 } },
  { name: "Rarible",        category: "Крипто", url: u => `https://rarible.com/user/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "MagicEden",      category: "Крипто", url: u => `https://magiceden.io/u/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Blur",           category: "Крипто", url: u => `https://blur.io/portfolio/${u}`,                notFound: { kind: "status",       code: 404 } },
  { name: "Robinhood",      category: "Финансы", url: u => `https://robinhood.com/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "eToro",          category: "Финансы", url: u => `https://www.etoro.com/people/${u}`,            notFound: { kind: "status",       code: 404 } },
  { name: "TradingView",    category: "Финансы", url: u => `https://www.tradingview.com/u/${u}/`,          notFound: { kind: "status",       code: 404 } },
  { name: "Seeking Alpha",  category: "Финансы", url: u => `https://seekingalpha.com/user/${u}/`,          notFound: { kind: "status",       code: 404 } },
  { name: "StockTwits",     category: "Финансы", url: u => `https://stocktwits.com/${u}`,                  notFound: { kind: "status",       code: 404 } },

  // ─── Стартапы / Профессиональные ─────────────────────────────────────────
  { name: "Product Hunt",   category: "Стартапы", url: u => `https://www.producthunt.com/@${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "AngelList",      category: "Стартапы", url: u => `https://angel.co/${u}`,                       notFound: { kind: "status",       code: 404 } },
  { name: "Crunchbase",     category: "Стартапы", url: u => `https://www.crunchbase.com/person/${u}`,      notFound: { kind: "status",       code: 404 } },
  { name: "Indie Hackers",  category: "Стартапы", url: u => `https://www.indiehackers.com/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "Wellfound",      category: "Стартапы", url: u => `https://wellfound.com/u/${u}`,                notFound: { kind: "status",       code: 404 } },
  { name: "Clarity.fm",     category: "Стартапы", url: u => `https://clarity.fm/${u}`,                    notFound: { kind: "status",       code: 404 } },
  { name: "Contra",         category: "Стартапы", url: u => `https://contra.com/${u}`,                    notFound: { kind: "status",       code: 404 } },
  { name: "Polywork",       category: "Стартапы", url: u => `https://www.polywork.com/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Glassdoor",      category: "Работа",   url: u => `https://www.glassdoor.com/profile/${u}`,     notFound: { kind: "status",       code: 404 } },
  { name: "Indeed",         category: "Работа",   url: u => `https://my.indeed.com/p/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Xing",           category: "Работа",   url: u => `https://www.xing.com/profile/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Upwork",         category: "Фриланс",  url: u => `https://www.upwork.com/freelancers/~${u}`,   notFound: { kind: "status",       code: 404 } },
  { name: "Freelancer",     category: "Фриланс",  url: u => `https://www.freelancer.com/u/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Fiverr",         category: "Фриланс",  url: u => `https://www.fiverr.com/${u}`,                notFound: { kind: "status",       code: 404 } },
  { name: "Toptal",         category: "Фриланс",  url: u => `https://www.toptal.com/resume/${u}`,         notFound: { kind: "status",       code: 404 } },
  { name: "PeoplePerHour",  category: "Фриланс",  url: u => `https://www.peopleperhour.com/freelancer/${u}`, notFound: { kind: "status",   code: 404 } },
  { name: "Guru",           category: "Фриланс",  url: u => `https://www.guru.com/freelancers/${u}/`,     notFound: { kind: "status",       code: 404 } },
  { name: "99designs",      category: "Фриланс",  url: u => `https://99designs.com/profiles/${u}`,        notFound: { kind: "status",       code: 404 } },
  { name: "Kwork",          category: "Фриланс",  url: u => `https://kwork.ru/user/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "FL.ru",          category: "Фриланс",  url: u => `https://www.fl.ru/users/${u}/`,              notFound: { kind: "status",       code: 404 } },

  // ─── Донаты / Монетизация ────────────────────────────────────────────────
  { name: "Patreon",        category: "Донаты", url: u => `https://www.patreon.com/${u}`,                  notFound: { kind: "status",       code: 404 } },
  { name: "Ko-fi",          category: "Донаты", url: u => `https://ko-fi.com/${u}`,                        notFound: { kind: "status",       code: 404 } },
  { name: "Buy Me a Coffee", category: "Донаты", url: u => `https://www.buymeacoffee.com/${u}`,            notFound: { kind: "status",       code: 404 } },
  { name: "Boosty",         category: "Донаты", url: u => `https://boosty.to/${u}`,                       notFound: { kind: "status",       code: 404 } },
  { name: "Open Collective", category: "Донаты", url: u => `https://opencollective.com/${u}`,              notFound: { kind: "status",       code: 404 } },
  { name: "GitHub Sponsors", category: "Донаты", url: u => `https://github.com/sponsors/${u}`,            notFound: { kind: "status",       code: 404 } },
  { name: "Streamelements",  category: "Донаты", url: u => `https://streamelements.com/${u}/tip`,         notFound: { kind: "status",       code: 404 } },
  { name: "Donationalerts",  category: "Донаты", url: u => `https://www.donationalerts.com/r/${u}`,       notFound: { kind: "status",       code: 404 } },
  { name: "Gumroad",        category: "Донаты", url: u => `https://${u}.gumroad.com`,                     notFound: { kind: "status",       code: 404 } },

  // ─── Магазины / Маркетплейсы ──────────────────────────────────────────────
  { name: "Etsy",           category: "Магазины", url: u => `https://www.etsy.com/shop/${u}`,              notFound: { kind: "status",       code: 404 } },
  { name: "eBay",           category: "Магазины", url: u => `https://www.ebay.com/usr/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Amazon",         category: "Магазины", url: u => `https://www.amazon.com/gp/profile/${u}`,      notFound: { kind: "status",       code: 404 } },
  { name: "Depop",          category: "Магазины", url: u => `https://www.depop.com/${u}/`,                 notFound: { kind: "status",       code: 404 } },
  { name: "Poshmark",       category: "Магазины", url: u => `https://poshmark.com/closet/${u}`,            notFound: { kind: "status",       code: 404 } },
  { name: "Vinted",         category: "Магазины", url: u => `https://www.vinted.com/member/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Mercari",        category: "Магазины", url: u => `https://www.mercari.com/u/${u}/`,             notFound: { kind: "status",       code: 404 } },
  { name: "Wish",           category: "Магазины", url: u => `https://www.wish.com/u/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "Storenvy",       category: "Магазины", url: u => `https://${u}.storenvy.com`,                   notFound: { kind: "status",       code: 404 } },
  { name: "BigCartel",      category: "Магазины", url: u => `https://${u}.bigcartel.com`,                  notFound: { kind: "status",       code: 404 } },
  { name: "Shopify",        category: "Магазины", url: u => `https://${u}.myshopify.com`,                  notFound: { kind: "status",       code: 404 } },
  { name: "AliExpress",     category: "Магазины", url: u => `https://www.aliexpress.com/store/${u}`,       notFound: { kind: "status",       code: 404 } },
  { name: "Wildberries",    category: "Магазины", url: u => `https://www.wildberries.ru/seller/${u}`,      notFound: { kind: "status",       code: 404 } },
  { name: "Ozon",           category: "Магазины", url: u => `https://www.ozon.ru/seller/${u}/`,            notFound: { kind: "status",       code: 404 } },
  { name: "Avito",          category: "Магазины", url: u => `https://www.avito.ru/user/${u}/profile`,      notFound: { kind: "status",       code: 404 } },

  // ─── Портфолио / Ссылки ───────────────────────────────────────────────────
  { name: "About.me",       category: "Портфолио", url: u => `https://about.me/${u}`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Linktree",       category: "Портфолио", url: u => `https://linktr.ee/${u}`,                    notFound: { kind: "status",       code: 404 } },
  { name: "Carrd",          category: "Портфолио", url: u => `https://${u}.carrd.co`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Bento",          category: "Портфолио", url: u => `https://bento.me/${u}`,                     notFound: { kind: "status",       code: 404 } },
  { name: "Campsite",       category: "Портфолио", url: u => `https://campsite.bio/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "Lnk.Bio",       category: "Портфолио", url: u => `https://lnk.bio/${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "Gravatar",       category: "Аватары",   url: u => `https://gravatar.com/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "AllMyLinks",     category: "Портфолио", url: u => `https://allmylinks.com/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Koji",           category: "Портфолио", url: u => `https://koji.to/${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "Beacons",        category: "Портфолио", url: u => `https://beacons.ai/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Stan.store",     category: "Портфолио", url: u => `https://stan.store/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Typeform",       category: "Портфолио", url: u => `https://${u}.typeform.com`,                 notFound: { kind: "status",       code: 404 } },
  { name: "Taplink",        category: "Портфолио", url: u => `https://taplink.cc/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Manylink",       category: "Портфолио", url: u => `https://manylink.co/@${u}`,                 notFound: { kind: "status",       code: 404 } },

  // ─── Путешествия ─────────────────────────────────────────────────────────
  { name: "Couchsurfing",   category: "Путешествия", url: u => `https://www.couchsurfing.com/people/${u}`, notFound: { kind: "status",      code: 404 } },
  { name: "Tripadvisor",    category: "Путешествия", url: u => `https://www.tripadvisor.com/Profile/${u}`, notFound: { kind: "status",      code: 404 } },
  { name: "TravelDiaries",  category: "Путешествия", url: u => `https://www.travellerspoint.com/users/${u}/`, notFound: { kind: "status",  code: 404 } },
  { name: "Nomad List",     category: "Путешествия", url: u => `https://nomadlist.com/@${u}`,              notFound: { kind: "status",       code: 404 } },
  { name: "Polarsteps",     category: "Путешествия", url: u => `https://www.polarsteps.com/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Maps.me",        category: "Путешествия", url: u => `https://tourism.maps.me/user/${u}`,        notFound: { kind: "status",       code: 404 } },
  { name: "Wayn",           category: "Путешествия", url: u => `https://www.wayn.com/${u}`,                notFound: { kind: "status",       code: 404 } },

  // ─── Еда / Кулинария ─────────────────────────────────────────────────────
  { name: "Allrecipes",     category: "Еда", url: u => `https://www.allrecipes.com/cook/${u}/`,            notFound: { kind: "status",       code: 404 } },
  { name: "Food.com",       category: "Еда", url: u => `https://www.food.com/friend/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "Cookpad",        category: "Еда", url: u => `https://cookpad.com/en/user/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "OpenTable",      category: "Еда", url: u => `https://www.opentable.com/profile/u/${u}`,         notFound: { kind: "status",       code: 404 } },

  // ─── Здоровье / Wellness ─────────────────────────────────────────────────
  { name: "Yelp",           category: "Отзывы", url: u => `https://www.yelp.com/user_details?userid=${u}`, notFound: { kind: "status",      code: 404 } },
  { name: "Google Maps",    category: "Отзывы", url: u => `https://www.google.com/maps/contrib/${u}`,      notFound: { kind: "status",       code: 404 } },
  { name: "Foursquare",     category: "Отзывы", url: u => `https://foursquare.com/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Swarm",          category: "Отзывы", url: u => `https://www.swarmapp.com/${u}`,                 notFound: { kind: "status",       code: 404 } },
  { name: "Zomato",         category: "Еда", url: u => `https://www.zomato.com/users/${u}`,                notFound: { kind: "status",       code: 404 } },

  // ─── Вопросы / Знания ────────────────────────────────────────────────────
  { name: "Answers.com",    category: "Знания", url: u => `https://www.answers.com/member/profile/${u}`,   notFound: { kind: "status",       code: 404 } },
  { name: "Yahoo Answers",  category: "Знания", url: u => `https://answers.yahoo.com/activity?show=${u}`,  notFound: { kind: "status",       code: 404 } },
  { name: "WikiHow",        category: "Знания", url: u => `https://www.wikihow.com/User:${u}`,             notFound: { kind: "bodyContains", text: "is not a registered user" } },
  { name: "Wikipedia",      category: "Знания", url: u => `https://en.wikipedia.org/wiki/User:${u}`,       notFound: { kind: "bodyContains", text: "hasn't created an account" } },
  { name: "Fandom",         category: "Знания", url: u => `https://www.fandom.com/u/${u}`,                 notFound: { kind: "status",       code: 404 } },

  // ─── Подкасты ────────────────────────────────────────────────────────────
  { name: "Anchor",         category: "Подкасты", url: u => `https://anchor.fm/${u}`,                      notFound: { kind: "status",       code: 404 } },
  { name: "Podbean",        category: "Подкасты", url: u => `https://${u}.podbean.com`,                    notFound: { kind: "status",       code: 404 } },
  { name: "Buzzsprout",     category: "Подкасты", url: u => `https://www.buzzsprout.com/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Spreaker",       category: "Подкасты", url: u => `https://www.spreaker.com/user/${u}`,          notFound: { kind: "status",       code: 404 } },

  // ─── Нетворкинг / Dating ─────────────────────────────────────────────────
  { name: "Tinder",         category: "Дейтинг", url: u => `https://tinder.com/@${u}`,                    notFound: { kind: "status",       code: 404 } },
  { name: "OkCupid",        category: "Дейтинг", url: u => `https://www.okcupid.com/profile/${u}`,        notFound: { kind: "status",       code: 404 } },
  { name: "Badoo",          category: "Дейтинг", url: u => `https://badoo.com/profile/${u}`,              notFound: { kind: "status",       code: 404 } },
  { name: "Plenty of Fish", category: "Дейтинг", url: u => `https://www.pof.com/viewprofile.aspx?profile_id=${u}`, notFound: { kind: "status", code: 404 } },
  { name: "Bumble",         category: "Дейтинг", url: u => `https://bumble.com/en/profile/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Hinge",          category: "Дейтинг", url: u => `https://hinge.co/${u}`,                       notFound: { kind: "status",       code: 404 } },

  // ─── Технологии / Гаджеты ─────────────────────────────────────────────────
  { name: "AnandTech",      category: "Технологии", url: u => `https://forums.anandtech.com/members/${u}.html`, notFound: { kind: "status", code: 404 } },
  { name: "Tom's Hardware", category: "Технологии", url: u => `https://forums.tomshardware.com/members/${u}.html`, notFound: { kind: "status", code: 404 } },
  { name: "GeekHack",       category: "Технологии", url: u => `https://geekhack.org/index.php?action=profile;user=${u}`, notFound: { kind: "status", code: 404 } },
  { name: "Instructables",  category: "Технологии", url: u => `https://www.instructables.com/member/${u}/`, notFound: { kind: "status",     code: 404 } },
  { name: "Hackaday",       category: "Технологии", url: u => `https://hackaday.io/${u}`,                  notFound: { kind: "status",       code: 404 } },
  { name: "Thingiverse",    category: "Технологии", url: u => `https://www.thingiverse.com/${u}`,          notFound: { kind: "status",       code: 404 } },
  { name: "Printables",     category: "Технологии", url: u => `https://www.printables.com/@${u}`,         notFound: { kind: "status",       code: 404 } },
  { name: "MakerWorld",     category: "Технологии", url: u => `https://makerworld.com/en/@${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "EEVblog",        category: "Технологии", url: u => `https://www.eevblog.com/forum/profile/?u=${u}`, notFound: { kind: "status",  code: 404 } },

  // ─── Политика / Новости ───────────────────────────────────────────────────
  { name: "Substack News",  category: "Новости", url: u => `https://${u}.substack.com`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Change.org",     category: "Петиции", url: u => `https://www.change.org/u/${u}`,               notFound: { kind: "status",       code: 404 } },
  { name: "Avaaz",          category: "Петиции", url: u => `https://www.avaaz.org/en/profile/${u}`,        notFound: { kind: "status",       code: 404 } },

  // ─── Волонтёрство / Некоммерческое ───────────────────────────────────────
  { name: "Idealist",       category: "НКО", url: u => `https://www.idealist.org/en/profile/${u}`,        notFound: { kind: "status",       code: 404 } },
  { name: "Catchafire",     category: "НКО", url: u => `https://www.catchafire.org/profiles/${u}/`,       notFound: { kind: "status",       code: 404 } },

  // ─── Разное ──────────────────────────────────────────────────────────────
  { name: "VSCO Film",      category: "Разное", url: u => `https://vsco.co/${u}`,                          notFound: { kind: "status",       code: 404 } },
  { name: "Pastebin",       category: "Разное", url: u => `https://pastebin.com/u/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Hastebin",       category: "Разное", url: u => `https://hastebin.com/u/${u}`,                   notFound: { kind: "status",       code: 404 } },
  { name: "Giphy",          category: "Разное", url: u => `https://giphy.com/${u}`,                        notFound: { kind: "status",       code: 404 } },
  { name: "Tenor",          category: "Разное", url: u => `https://tenor.com/users/${u}`,                  notFound: { kind: "status",       code: 404 } },
  { name: "ProductHunt",    category: "Разное", url: u => `https://www.producthunt.com/@${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Wattpad",        category: "Разное", url: u => `https://www.wattpad.com/user/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Amino",          category: "Разное", url: u => `https://aminoapps.com/u/${u}`,                  notFound: { kind: "status",       code: 404 } },
  { name: "Cake",           category: "Разное", url: u => `https://cakeresume.com/users/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Knowem",         category: "Разное", url: u => `https://knowem.com/checkusernames.php?u=${u}`,  notFound: { kind: "status",       code: 404 } },
  { name: "NameChk",        category: "Разное", url: u => `https://www.namechk.com/u/${u}`,                notFound: { kind: "status",       code: 404 } },
  { name: "CheckUsernames", category: "Разное", url: u => `https://checkusernames.com/`,                  notFound: { kind: "status",       code: 404 } },
  { name: "Reverbnation",   category: "Разное", url: u => `https://www.reverbnation.com/${u}`,             notFound: { kind: "status",       code: 404 } },
  { name: "Vero",           category: "Разное", url: u => `https://vero.co/${u}`,                          notFound: { kind: "status",       code: 404 } },
  { name: "Lasso",          category: "Разное", url: u => `https://www.joinlasso.com/${u}`,                notFound: { kind: "status",       code: 404 } },
  { name: "Turo",           category: "Разное", url: u => `https://turo.com/us/en/drivers/${u}`,           notFound: { kind: "status",       code: 404 } },
  { name: "Airbnb",         category: "Разное", url: u => `https://www.airbnb.com/users/show/${u}`,        notFound: { kind: "status",       code: 404 } },
  { name: "Rover",          category: "Разное", url: u => `https://www.rover.com/members/${u}/`,           notFound: { kind: "status",       code: 404 } },
  { name: "DoorDash",       category: "Разное", url: u => `https://www.doordash.com/dasher/${u}/`,         notFound: { kind: "status",       code: 404 } },
  { name: "Lyft",           category: "Разное", url: u => `https://www.lyft.com/drivers/${u}`,             notFound: { kind: "status",       code: 404 } },
];
